### ISSUE TITLE
update or remove Gemfile.lock

### ISSUE THREAD

**Issue by rosskevin** [dreamins/Route53DDNS-ruby#4]
Not really a bug, but you might want to either update the Gemfile.lock or remove it.  It's pretty old now and fails to install on Ubuntu due to a curb error on 0.8.0.  A simple bundle update solves it, or the instructions in the readme with bundle install would work if there wasn't a lock file.

**Comment by dreamins** [comment]
Thanks.

I would prefer to leave the Gemfile.lock, the idea is to have fixed set of dependencies that are known to work. I'll update the file though (there is actually a merge request from 3 months ago that I somehow missed).

Thanks again.
